# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LidarTileMaker
                                 A QGIS plugin
 The plugin creates a vector file containing the polygons of the tiles of a lidar campaign starting from the raster data (DSM and DTM).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2019-07-01
        copyright            : (C) 2019 by Gter srl
        email                : assistenzagis@gter.it
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LidarTileMaker class from file LidarTileMaker.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .lidar_tile_maker import LidarTileMaker
    return LidarTileMaker(iface)
